id: android-sdk-version-misconfiguration

info:
  name: Android SDK Version Validation
  author: mohammad
  severity: medium
  description: |
    Detects missing or misconfigured `minSdkVersion` and `targetSdkVersion` in AndroidManifest.xml or Gradle files.
    Proper configuration is necessary to enforce security measures from newer Android versions.
  tags: android, manifest, gradle, security, misconfiguration

file:
  - extensions:
      - xml
      - gradle
    matchers:
      # Detect missing or weak minSdkVersion in AndroidManifest.xml
      - type: regex
        regex:
          - '<uses-sdk\s*[^>]*>'
          - '<uses-sdk[^>]*android:minSdkVersion\s*=\s*"[0-9]|1[0-7]"' # Detects weak versions (0-17)
        condition: or

      # Detect missing or weak targetSdkVersion in AndroidManifest.xml
      - type: regex
        regex:
          - '<uses-sdk\s*[^>]*>'
          - '<uses-sdk[^>]*android:targetSdkVersion\s*=\s*"[0-9]|1[0-9]|2[0-5]"' # Detects outdated versions (below 26)
        condition: or

      # Detect weak or missing SDK versions in Gradle files
      - type: regex
        regex:
          - 'minSdkVersion\s+[0-9]|1[0-7]'   # Weak minSdkVersion
          - 'targetSdkVersion\s+[0-9]|1[0-9]|2[0-5]'  # Outdated targetSdkVersion
        condition: or