id: android-ssl-misconfiguration
info:
  name: Android SSL Misconfiguration Detection
  author: mohammad
  severity: high
  description: |
    Detects improper SSL configuration or usage of insecure SSL protocols/ciphers, which may lead to Man-in-the-Middle (MITM) attacks or data interception.
  tags: android, security, ssl, misconfiguration, https

file:
  - extensions:
      - smali
      - java
    matchers:
      # Detects usage of insecure SSL context initialization
      - type: regex
        regex:
          - 'Ljavax/net/ssl/SSLContext;->getInstance\(Ljava/lang/String;\)' # Checks for SSLContext initialization
        condition: or
      # Detects SSL socket factories being used without proper validation
      - type: regex
        regex:
          - 'Ljavax/net/ssl/SSLSocketFactory;->setDefault\(Ljavax/net/ssl/SSLSocketFactory;\)' # Checks for setting default SSL factory
        condition: or
      # Detects the usage of insecure SSL protocols like SSLv3 or TLSv1
      - type: regex
        regex:
          - '"SSLv3"'
          - '"TLSv1"'
          - '"TLSv1_1"'
        condition: or
      # Detects SSL certificate validation bypass
      - type: regex
        regex:
          - 'trustAllCertificates\(.*?\)' # Bypassing SSL certificate verification
        condition: or